# Generated by Django 2.2.1 on 2019-06-28 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20190628_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snippets.Person')),
                ('enroll_number', models.CharField(blank=True, max_length=10)),
                ('friends', models.ManyToManyField(related_name='_student_friends_+', to='snippets.Student')),
            ],
            bases=('snippets.person',),
        ),
    ]
