# Generated by Django 2.2.1 on 2019-06-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('type', models.SmallIntegerField(choices=[(1, 'OWNER'), (2, 'STAFF')], default=2)),
                ('staffs', models.ManyToManyField(to='snippets.Employee')),
            ],
        ),
    ]
